### ISSUE TITLE
bug - Elastic Sources - metrics generation fails for raw/from based Elastic Sources definition (shared and dedicated)

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#150]
I used elastic sources for the very first time. Entities appear in the overview table with lag values, last event and last ingest.
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/f479db75-9753-410c-8c61-bae407f217d6)

When I open the details view for an entity, metrics are not shown.

![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/865b3fba-4953-4a68-a9f1-fb7ca30649be)

When I change the dropdown to "Splunk query" everything shows up.
Latency & Volume metrics (from the 3rd tab) do not show up as well.

**Comment by sebwurl** [comment]
I created dedicated elastic sources. The search mode is raw and searches all look like this:
`index=my_index sourcetype=my_sourcetype my_field=my_value`

**Comment by guilhemmarchand** [comment]
all right - might be a regression we have not seen with the least privileges approach from 2.0.34.
Will follow up

**Comment by guilhemmarchand** [comment]
Fixed in version 2.0.38 @sebwurl

**Comment by sebwurl** [comment]
Hi,
I recognized that this issue still exists for some entities.
To me, it looks like Elastic Sources that end up in an entity with three colons don't write metrics, e.g. my:elastic:source:entity.
Entities from Elastic Sources with just two colons seem to work.

Native entities created by hybrid trackers show metrics, although the entity names include three colons.

**Comment by guilhemmarchand** [comment]
Hi @sebwurl 

> Do I have to re-create the Elastic Sources?

I believe so but I would need to re-check the bug fix details.

Could it be possible for you to test with rec-creating at least one Elastic entity to verify?

**Comment by sebwurl** [comment]
Re-creating did it, thanks :)
