### ISSUE TITLE
bug/enhancement - avoid disabling access to the acnknowledgement if it is still active althrough the entity is back in green state

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#96]
In v2.0.19 I disabled the **Remove Ack behaviour** feature. However, when the status of an entity flips to green, the acknowledgement is removed. Having a look at an active acknowledgment set by an alert, the UI says it is unsticky.

**Comment by guilhemmarchand** [comment]
Hum @sebwurl I think I am following you sorry ;-)

The configuration says:

```
Automatically removes an Acknowledgment when the entity is back in green state, even if it has not expired yet (unless sticky Ack)
```

So, unless it is a sticky Ack, when the entity goes back to green, the default expected behavior, and unless this config is updated, is that the Ack would be removed.

Perhaps I am missing your question?

<img width="823" alt="image" src="https://user-images.githubusercontent.com/7503059/232829813-85094d4f-5caf-4867-b79d-482a252940ef.png">

**Comment by guilhemmarchand** [comment]
NB: not related to your question, but your question actually helped identify a regression in 2.0.21 with the Ack tracker: https://github.com/trackme-limited/trackme-report-issues/issues/97
2.0.22 will be released today to address this - thanks for that!

**Comment by guilhemmarchand** [comment]
I think it's working as expected @sebwurl 

1. If the Ack is unsticky, and the entities returns to green BUT the Ack has not expired, and the option "Remove Ack behaviour" is set to No (default)

The logs will show:

```
2023-04-18 16:41:03,068 INFO trackmeacktracker.py generate 205 tenant_id="feeds-tracking", object_category="splk-dsm", object="eventgen-linux:linux_secure", object_state="green", entity_has_returned_to_green="True"
```

The Ack is not removed which is expected as it's not expired.

2. Same but the option is set to true

The Ack is removed:

```
2023-04-18 16:45:47,303 INFO trackmeacktracker.py generate 205 tenant_id="feeds-tracking", object_category="splk-dsm", object="eventgen-linux:linux_secure", object_state="green", entity_has_returned_to_green="True"
2023-04-18 16:45:47,303 INFO trackmeacktracker.py generate 237 Ack with key="643ec0affe74c55b6130d9de" is active and unsticky, the entity has returned to green, forcing its expiration now
2023-04-18 16:45:47,309 INFO trackmeacktracker.py generate 252 Ack with key="643ec0affe74c55b6130d9de" for object="eventgen-linux:linux_secure" object_category="splk-dsm" was updated successfully
```

On the opposite, if the Ack is unsticky, the entity is back to green and the ack is expired, then it is removed:

```
2023-04-18 16:56:37,989 INFO trackmeacktracker.py generate 205 tenant_id="feeds-tracking", object_category="splk-dsm", object="eventgen-linux:linux_secure", object_state="green", entity_has_returned_to_green="True"
2023-04-18 16:56:37,989 INFO trackmeacktracker.py generate 280 Ack with key="643ec0affe74c55b6130d9de" is expired since 19.99 seconds, updating the record now
2023-04-18 16:56:38,089 INFO trackmeacktracker.py generate 295 Ack with key="643ec0affe74c55b6130d9de" for object="eventgen-linux:linux_secure" object_category="splk-dsm" was updated successfully
```

**Comment by sebwurl** [comment]
You describe what I was expecting :)

**Comment by sebwurl** [comment]
Sorry, somehow I closed this issue...
With sample 1. you describe exactly what I was expecting. "Remove Ack behaviour" is set to No and not expired, so I have to go to the entity and remove the ack manually.

What I'm experiencing is:
(1) Entity is alerted and the ack is set
(2) KPIs normalize and thresholds are okay. The status icon flips to green and the ack button is greyed out.
(3) KPIs worsen and the Ack icon is shown again, but there is no alert fired. The ack button is available, but its entries show the timestamp from the first flip. So I think TrackMe still has the first ack active, but it is not shown and not accessible via the UI.

**Comment by guilhemmarchand** [comment]
Understood and agreed now - the UI should still allow access to the Ack if it is still active.

Fixed in version 2.0.22

**Comment by sebwurl** [comment]
Great. I only noticed this detailed behaviour in a later review. That's why my first post was a bit unclear :)

**Comment by sebwurl** [comment]
Hi, 
I think it is still not working as expected when the **Remove Ack behaviour** is set to "Yes"(v2.0.27).
I want to use the **Remove Ack behaviour**=Yes approach to avoid multiple alerts in case of frequent status flipping (and I don't want to use Splunk the suppression). The entity should be alerted once and stay in ack to avoid alerts, until someone reviewes it and removes the ack.

I'm experiencing this:
(1) Entity is alerted and the ack is set.
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/4864d017-7e2e-4349-872b-419354108b58)
2) KPIs normalize and thresholds are okay, the ack is still active. But the icon is "wrong". In this case the user does not know that ack is active and that the entity has to be reviewed/manually un-acknowledged.
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/b9d6cf11-2aa9-461e-98d7-87ad8067d418)
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/8c1d35fb-d412-4c65-90bb-52480994c881)

**Comment by guilhemmarchand** [comment]
Hi @sebwurl 

Copy that - and agreed, this would make sense and will improve the behaviour.

Logged here:
https://github.com/trackme-limited/trackme-report-issues/issues/116
